/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthControllerCheck200Response,
  HealthControllerCheck503Response,
  SystemSettings,
} from '../models/index';
import {
    HealthControllerCheck200ResponseFromJSON,
    HealthControllerCheck200ResponseToJSON,
    HealthControllerCheck503ResponseFromJSON,
    HealthControllerCheck503ResponseToJSON,
    SystemSettingsFromJSON,
    SystemSettingsToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * システムの設定を返却する
     */
    async getSystemSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemSettings>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v0/system/settings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemSettingsFromJSON(jsonValue));
    }

    /**
     * システムの設定を返却する
     */
    async getSystemSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemSettings> {
        const response = await this.getSystemSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async healthControllerCheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthControllerCheck200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthControllerCheck200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async healthControllerCheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthControllerCheck200Response> {
        const response = await this.healthControllerCheckRaw(initOverrides);
        return await response.value();
    }

}
