/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityPubPost
 */
export interface ActivityPubPost {
    /**
     * ActivityPubで一意の値
     * @type {string}
     * @memberof ActivityPubPost
     */
    objectId: string;
}

/**
 * Check if a given object implements the ActivityPubPost interface.
 */
export function instanceOfActivityPubPost(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "objectId" in value;

    return isInstance;
}

export function ActivityPubPostFromJSON(json: any): ActivityPubPost {
    return ActivityPubPostFromJSONTyped(json, false);
}

export function ActivityPubPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityPubPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objectId': json['object_id'],
    };
}

export function ActivityPubPostToJSON(value?: ActivityPubPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'object_id': value.objectId,
    };
}

