/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ATProtocolPost
 */
export interface ATProtocolPost {
    /**
     * 
     * @type {string}
     * @memberof ATProtocolPost
     */
    cid: string;
    /**
     * ATProtocolで一意の値
     * @type {string}
     * @memberof ATProtocolPost
     */
    uri: string;
}

/**
 * Check if a given object implements the ATProtocolPost interface.
 */
export function instanceOfATProtocolPost(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cid" in value;
    isInstance = isInstance && "uri" in value;

    return isInstance;
}

export function ATProtocolPostFromJSON(json: any): ATProtocolPost {
    return ATProtocolPostFromJSONTyped(json, false);
}

export function ATProtocolPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ATProtocolPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cid': json['cid'],
        'uri': json['uri'],
    };
}

export function ATProtocolPostToJSON(value?: ATProtocolPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cid': value.cid,
        'uri': value.uri,
    };
}

