/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthToken
 */
export interface AuthToken {
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    authToken: string;
    /**
     * auth_tokenの有効期限
     * @type {Date}
     * @memberof AuthToken
     */
    expiresAt?: Date;
}

/**
 * Check if a given object implements the AuthToken interface.
 */
export function instanceOfAuthToken(value: object): boolean {
    if (!('accessToken' in value)) return false;
    if (!('authToken' in value)) return false;
    return true;
}

export function AuthTokenFromJSON(json: any): AuthToken {
    return AuthTokenFromJSONTyped(json, false);
}

export function AuthTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthToken {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'authToken': json['auth_token'],
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
    };
}

export function AuthTokenToJSON(value?: AuthToken | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access_token': value['accessToken'],
        'auth_token': value['authToken'],
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
    };
}

