/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePost
 */
export interface CreatePost {
    /**
     * 引用元ID
     * @type {string}
     * @memberof CreatePost
     */
    originalPostId?: string;
    /**
     * 本文
     * @type {string}
     * @memberof CreatePost
     */
    text?: string;
}

/**
 * Check if a given object implements the CreatePost interface.
 */
export function instanceOfCreatePost(value: object): boolean {
    return true;
}

export function CreatePostFromJSON(json: any): CreatePost {
    return CreatePostFromJSONTyped(json, false);
}

export function CreatePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePost {
    if (json == null) {
        return json;
    }
    return {
        
        'originalPostId': json['original_post_id'] == null ? undefined : json['original_post_id'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function CreatePostToJSON(value?: CreatePost | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'original_post_id': value['originalPostId'],
        'text': value['text'],
    };
}

