/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationCodeRequest
 */
export interface InvitationCodeRequest {
    /**
     * 招待コード
     * @type {string}
     * @memberof InvitationCodeRequest
     */
    invitationCode: string;
}

/**
 * Check if a given object implements the InvitationCodeRequest interface.
 */
export function instanceOfInvitationCodeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "invitationCode" in value;

    return isInstance;
}

export function InvitationCodeRequestFromJSON(json: any): InvitationCodeRequest {
    return InvitationCodeRequestFromJSONTyped(json, false);
}

export function InvitationCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'invitationCode': json['invitation_code'],
    };
}

export function InvitationCodeRequestToJSON(value?: InvitationCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'invitation_code': value.invitationCode,
    };
}

