/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Invitation
 */
export interface Invitation {
    /**
     * 招待コード
     * @type {string}
     * @memberof Invitation
     */
    code: string;
    /**
     * 招待コードの発行日時
     * @type {Date}
     * @memberof Invitation
     */
    issuedAt: Date;
    /**
     * 招待コードの使用日時
     * @type {Date}
     * @memberof Invitation
     */
    usedAt?: Date;
}

/**
 * Check if a given object implements the Invitation interface.
 */
export function instanceOfInvitation(value: object): boolean {
    if (!('code' in value)) return false;
    if (!('issuedAt' in value)) return false;
    return true;
}

export function InvitationFromJSON(json: any): Invitation {
    return InvitationFromJSONTyped(json, false);
}

export function InvitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invitation {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'issuedAt': (new Date(json['issued_at'])),
        'usedAt': json['used_at'] == null ? undefined : (new Date(json['used_at'])),
    };
}

export function InvitationToJSON(value?: Invitation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'issued_at': ((value['issuedAt']).toISOString()),
        'used_at': value['usedAt'] == null ? undefined : ((value['usedAt']).toISOString()),
    };
}

