/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitationCodeRequest
 */
export interface InvitationCodeRequest {
    /**
     * 招待コード
     * @type {string}
     * @memberof InvitationCodeRequest
     */
    invitationCode: string;
}

/**
 * Check if a given object implements the InvitationCodeRequest interface.
 */
export function instanceOfInvitationCodeRequest(value: object): boolean {
    if (!('invitationCode' in value)) return false;
    return true;
}

export function InvitationCodeRequestFromJSON(json: any): InvitationCodeRequest {
    return InvitationCodeRequestFromJSONTyped(json, false);
}

export function InvitationCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'invitationCode': json['invitation_code'],
    };
}

export function InvitationCodeRequestToJSON(value?: InvitationCodeRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invitation_code': value['invitationCode'],
    };
}

