/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordReset
 */
export interface PasswordReset {
    /**
     * ユーザーID
     * @type {number}
     * @memberof PasswordReset
     */
    userId: number;
    /**
     * リセットコード
     * @type {string}
     * @memberof PasswordReset
     */
    code: string;
    /**
     * 新しいパスワード
     * @type {string}
     * @memberof PasswordReset
     */
    newPassword: string;
}

/**
 * Check if a given object implements the PasswordReset interface.
 */
export function instanceOfPasswordReset(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "newPassword" in value;

    return isInstance;
}

export function PasswordResetFromJSON(json: any): PasswordReset {
    return PasswordResetFromJSONTyped(json, false);
}

export function PasswordResetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordReset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'code': json['code'],
        'newPassword': json['new_password'],
    };
}

export function PasswordResetToJSON(value?: PasswordReset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
        'code': value.code,
        'new_password': value.newPassword,
    };
}

