/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Post } from './Post';
import {
    PostFromJSON,
    PostFromJSONTyped,
    PostToJSON,
} from './Post';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface PostResponse
 */
export interface PostResponse {
    /**
     * 
     * @type {string}
     * @memberof PostResponse
     */
    id: string;
    /**
     * リポスト|引用元ID|オリジナルには含まれません。
     * @type {string}
     * @memberof PostResponse
     */
    originalPostId: string;
    /**
     * リプライ先ID|リプライでない場合は含まれません。
     * @type {string}
     * @memberof PostResponse
     */
    replyToPostId: string;
    /**
     * 
     * @type {User}
     * @memberof PostResponse
     */
    author: User;
    /**
     * 本文|空orNullの場合はRTです。
     * @type {string}
     * @memberof PostResponse
     */
    text: string;
    /**
     * 
     * @type {Date}
     * @memberof PostResponse
     */
    postedAt: Date;
    /**
     * 
     * @type {Post}
     * @memberof PostResponse
     */
    originalPost: Post;
    /**
     * リポスト済み
     * @type {boolean}
     * @memberof PostResponse
     */
    reposted: boolean;
    /**
     * リポスト数
     * @type {number}
     * @memberof PostResponse
     */
    repostCount: number;
    /**
     * お気に入り登録済み
     * @type {boolean}
     * @memberof PostResponse
     */
    favorited: boolean;
    /**
     * お気に入り数
     * @type {number}
     * @memberof PostResponse
     */
    favoriteCount: number;
}

/**
 * Check if a given object implements the PostResponse interface.
 */
export function instanceOfPostResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "originalPostId" in value;
    isInstance = isInstance && "replyToPostId" in value;
    isInstance = isInstance && "author" in value;
    isInstance = isInstance && "text" in value;
    isInstance = isInstance && "postedAt" in value;
    isInstance = isInstance && "originalPost" in value;
    isInstance = isInstance && "reposted" in value;
    isInstance = isInstance && "repostCount" in value;
    isInstance = isInstance && "favorited" in value;
    isInstance = isInstance && "favoriteCount" in value;

    return isInstance;
}

export function PostResponseFromJSON(json: any): PostResponse {
    return PostResponseFromJSONTyped(json, false);
}

export function PostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'originalPostId': json['original_post_id'],
        'replyToPostId': json['reply_to_post_id'],
        'author': UserFromJSON(json['author']),
        'text': json['text'],
        'postedAt': (new Date(json['posted_at'])),
        'originalPost': PostFromJSON(json['original_post']),
        'reposted': json['reposted'],
        'repostCount': json['repost_count'],
        'favorited': json['favorited'],
        'favoriteCount': json['favorite_count'],
    };
}

export function PostResponseToJSON(value?: PostResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'original_post_id': value.originalPostId,
        'reply_to_post_id': value.replyToPostId,
        'author': UserToJSON(value.author),
        'text': value.text,
        'posted_at': (value.postedAt.toISOString()),
        'original_post': PostToJSON(value.originalPost),
        'reposted': value.reposted,
        'repost_count': value.repostCount,
        'favorited': value.favorited,
        'favorite_count': value.favoriteCount,
    };
}

