/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreUserRequest
 */
export interface PreUserRequest {
    /**
     * 表示名
     * @type {string}
     * @memberof PreUserRequest
     */
    name: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof PreUserRequest
     */
    email: string;
}

/**
 * Check if a given object implements the PreUserRequest interface.
 */
export function instanceOfPreUserRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function PreUserRequestFromJSON(json: any): PreUserRequest {
    return PreUserRequestFromJSONTyped(json, false);
}

export function PreUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
    };
}

export function PreUserRequestToJSON(value?: PreUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
    };
}

