/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreUserRequest
 */
export interface PreUserRequest {
    /**
     * 表示名
     * @type {string}
     * @memberof PreUserRequest
     */
    name: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof PreUserRequest
     */
    email: string;
}

/**
 * Check if a given object implements the PreUserRequest interface.
 */
export function instanceOfPreUserRequest(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('email' in value)) return false;
    return true;
}

export function PreUserRequestFromJSON(json: any): PreUserRequest {
    return PreUserRequestFromJSONTyped(json, false);
}

export function PreUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
    };
}

export function PreUserRequestToJSON(value?: PreUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
    };
}

