/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfile
 */
export interface UpdateProfile {
    /**
     * 表示名
     * @type {string}
     * @memberof UpdateProfile
     */
    name?: string;
    /**
     * bio
     * @type {object}
     * @memberof UpdateProfile
     */
    bio?: object;
}

/**
 * Check if a given object implements the UpdateProfile interface.
 */
export function instanceOfUpdateProfile(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateProfileFromJSON(json: any): UpdateProfile {
    return UpdateProfileFromJSONTyped(json, false);
}

export function UpdateProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
    };
}

export function UpdateProfileToJSON(value?: UpdateProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'bio': value.bio,
    };
}

