/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserWithFollows
 */
export interface UserWithFollows {
    /**
     * 
     * @type {number}
     * @memberof UserWithFollows
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserWithFollows
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithFollows
     */
    username: string;
    /**
     * 
     * @type {Date}
     * @memberof UserWithFollows
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserWithFollows
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithFollows
     */
    profileImageUrl: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserWithFollows
     */
    _protected: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserWithFollows
     */
    url: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserWithFollows
     */
    verified: boolean;
    /**
     * フォロワー数
     * @type {number}
     * @memberof UserWithFollows
     */
    followersCount?: number;
    /**
     * フォロー数
     * @type {number}
     * @memberof UserWithFollows
     */
    followingCount?: number;
}

/**
 * Check if a given object implements the UserWithFollows interface.
 */
export function instanceOfUserWithFollows(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "profileImageUrl" in value;
    isInstance = isInstance && "_protected" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "verified" in value;

    return isInstance;
}

export function UserWithFollowsFromJSON(json: any): UserWithFollows {
    return UserWithFollowsFromJSONTyped(json, false);
}

export function UserWithFollowsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithFollows {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'username': json['username'],
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'],
        'profileImageUrl': json['profile_image_url'],
        '_protected': json['protected'],
        'url': json['url'],
        'verified': json['verified'],
        'followersCount': !exists(json, 'followers_count') ? undefined : json['followers_count'],
        'followingCount': !exists(json, 'following_count') ? undefined : json['following_count'],
    };
}

export function UserWithFollowsToJSON(value?: UserWithFollows | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'username': value.username,
        'created_at': (value.createdAt.toISOString()),
        'description': value.description,
        'profile_image_url': value.profileImageUrl,
        'protected': value._protected,
        'url': value.url,
        'verified': value.verified,
        'followers_count': value.followersCount,
        'following_count': value.followingCount,
    };
}

