/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRequest
 */
export interface UserRequest {
    /**
     * メールアドレス
     * @type {string}
     * @memberof UserRequest
     */
    email: string;
    /**
     * 認証コード
     * @type {string}
     * @memberof UserRequest
     */
    code: string;
    /**
     * ユーザーID
     * @type {string}
     * @memberof UserRequest
     */
    username: string;
    /**
     * パスワード
     * @type {string}
     * @memberof UserRequest
     */
    password: string;
    /**
     * 招待コード
     * @type {string}
     * @memberof UserRequest
     */
    invitationCode?: string;
}

/**
 * Check if a given object implements the UserRequest interface.
 */
export function instanceOfUserRequest(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('code' in value)) return false;
    if (!('username' in value)) return false;
    if (!('password' in value)) return false;
    return true;
}

export function UserRequestFromJSON(json: any): UserRequest {
    return UserRequestFromJSONTyped(json, false);
}

export function UserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
        'username': json['username'],
        'password': json['password'],
        'invitationCode': json['invitation_code'] == null ? undefined : json['invitation_code'],
    };
}

export function UserRequestToJSON(value?: UserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'code': value['code'],
        'username': value['username'],
        'password': value['password'],
        'invitation_code': value['invitationCode'],
    };
}

