/* tslint:disable */
/* eslint-disable */
/**
 * Cuculus API
 * The Cuculus API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyCodeRequest
 */
export interface VerifyCodeRequest {
    /**
     * メールアドレス
     * @type {string}
     * @memberof VerifyCodeRequest
     */
    email: string;
    /**
     * 認証コード
     * @type {string}
     * @memberof VerifyCodeRequest
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyCodeRequest interface.
 */
export function instanceOfVerifyCodeRequest(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('code' in value)) return false;
    return true;
}

export function VerifyCodeRequestFromJSON(json: any): VerifyCodeRequest {
    return VerifyCodeRequestFromJSONTyped(json, false);
}

export function VerifyCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function VerifyCodeRequestToJSON(value?: VerifyCodeRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'code': value['code'],
    };
}

